language: scala
sudo: false
scala:
   - 2.12.11
   - 2.13.1
matrix:
  include:
  - jdk: openjdk11
    scala: 2.12.11
jdk:
  - openjdk8
script:
  - sbt "++ ${TRAVIS_SCALA_VERSION}!" scalafmtCheck test:scalafmtCheck scalafmtSbtCheck test
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
